---
# Configuration for math problem generation parameters
# Levels are defined independently, then referenced by model sizes

# Define difficulty levels for all problem types
levels:
  algebra_linear_equation:
    level_1:
      variables: 2
      min_ops: 1
      max_ops: 1
      min_length: 8
      max_length: 10
    level_2:
      variables: 3
      min_ops: 2
      max_ops: 3
      min_length: 10
      max_length: 12
    level_3:
      variables: 4
      min_ops: 2
      max_ops: 3
      min_length: 12
      max_length: 14
    level_4:
      variables: 5
      min_ops: 2
      max_ops: 3
      min_length: 14
      max_length: 16
    level_5:
      variables: 6
      min_ops: 3
      max_ops: 4
      min_length: 16
      max_length: 20
  
  algebra_polynomial_roots:
    level_1:
      degree: 3
      min_ops: 1
      max_ops: 1
      min_length: 3
      max_length: 5
    level_2:
      degree: 4
      min_ops: 2
      max_ops: 3
      min_length: 5
      max_length: 10
    level_3:
      degree: 5
      min_ops: 2
      max_ops: 3
      min_length: 9
      max_length: 12
    level_4:
      degree: 6
      min_ops: 2
      max_ops: 3
      min_length: 12
      max_length: 15
    level_5:
      degree: 7
      min_ops: 2
      max_ops: 3
      min_length: 15
      max_length: 20
  
  arithmetic_mixed:
    level_1:
      type: "rational"
      min_ops: 1
      max_ops: 1
      min_length: 4
      max_length: 9
    level_2:
      type: "rational"
      min_ops: 1
      max_ops: 1
      min_length: 10
      max_length: 14
    level_3:
      type: "rational"
      min_ops: 1
      max_ops: 1
      min_length: 14
      max_length: 16
    level_4:
      type: "rational"
      min_ops: 1
      max_ops: 1
      min_length: 16
      max_length: 20
    level_5:
      type: "rational"
      min_ops: 2
      max_ops: 2
      min_length: 20
      max_length: 25
  
  arithmetic_list_prime_factors:
    level_1:
      max_value: 25
      min_ops: 1
      max_ops: 1
      min_length: 4
      max_length: 7
    level_2:
      max_value: 100
      min_ops: 1
      max_ops: 1
      min_length: 8
      max_length: 12
    level_3:
      max_value: 200
      min_ops: 1
      max_ops: 1
      min_length: 12
      max_length: 15
    level_4:
      max_value: 400
      min_ops: 1
      max_ops: 1
      min_length: 15
      max_length: 18
    level_5:
      max_value: 800
      min_ops: 1
      max_ops: 2
      min_length: 18
      max_length: 25
  
  arithmetic_gcd:
    level_1:
      min_ops: 1
      max_ops: 1
      min_length: 4
      max_length: 7
    level_2:
      min_ops: 1
      max_ops: 1
      min_length: 10
      max_length: 12
    level_3:
      min_ops: 1
      max_ops: 1
      min_length: 15
      max_length: 20
    level_4:
      min_ops: 1
      max_ops: 1
      min_length: 20
      max_length: 25
    level_5:
      min_ops: 1
      max_ops: 2
      min_length: 25
      max_length: 30

# Model-specific configurations mapping difficulty to levels
models:
  7B:
    medium: level_1  # corresponds to difficulty level 1
    hard: level_2    # corresponds to difficulty level 2
    exhard: level_3  # corresponds to difficulty level 3
  
  32B:
    medium: level_2  # corresponds to difficulty level 2
    hard: level_3    # corresponds to difficulty level 3
    exhard: level_4  # corresponds to difficulty level 4 