---
# Configuration for math problem generation parameters
# Levels are defined independently, then referenced by model sizes

# Define difficulty levels for all problem types
levels:
  basic:
    level_1:
      min_length: 6
      max_length: 10
    level_2:
      min_length: 11
      max_length: 15
    level_3:
      min_length: 16
      max_length: 19
    level_4:
      min_length: 20
      max_length: 25
    level_5:
      min_length: 26
      max_length: 30
  polygon:
    level_1:
      min_length: 6
      max_length: 10
    level_2:
      min_length: 11
      max_length: 15
    level_3:
      min_length: 16
      max_length: 19
    level_4:
      min_length: 20
      max_length: 25
    level_5:
      min_length: 26
      max_length: 30
  circle:
    level_1:
      min_length: 6
      max_length: 10
    level_2:
      min_length: 11
      max_length: 15
    level_3:
      min_length: 16
      max_length: 19
    level_4:
      min_length: 20
      max_length: 25
    level_5:
      min_length: 26
      max_length: 30
  triangle:
    level_1:
      min_length: 6
      max_length: 10
    level_2:
      min_length: 11
      max_length: 15
    level_3:
      min_length: 16
      max_length: 19
    level_4:
      min_length: 20
      max_length: 25
    level_5:
      min_length: 26
      max_length: 30

# Model-specific configurations mapping difficulty to levels
models:
  7B:
    medium: level_1  # corresponds to difficulty level 1
    hard: level_2    # corresponds to difficulty level 2
    exhard: level_3  # corresponds to difficulty level 3
  
  32B:
    medium: level_2  # corresponds to difficulty level 2
    hard: level_3    # corresponds to difficulty level 3
    exhard: level_4  # corresponds to difficulty level 4 
